# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "npm install @rollup/rollup-linux-x64-gnu --save-optional",
  "npm install @swc/core-linux-x64-gnu --save-optional"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"